import argparse
import logging
from pathlib import Path
from typing import Sequence
from time import perf_counter

from knowledge_assistant.chunking import chunk_document
from knowledge_assistant.document_loader import load_documents
from knowledge_assistant.embeddings import (
    EmbeddingProvider,
    SentenceTransformerEmbeddingProvider,
)
from knowledge_assistant.vector_store import LanceDBVectorStore
from knowledge_assistant.formatters import ConsoleFormatter
from knowledge_assistant.retrieval import Retriever
import os
from knowledge_assistant.answering import AnswerService
from knowledge_assistant.llm import (
    DEFAULT_OLLAMA_HOST,
    DEFAULT_OLLAMA_MODEL,
    LLMProvider,
    OllamaProvider,
)
from knowledge_assistant.prompt_builder import PromptBuilder
from knowledge_assistant.config import Settings, get_settings
from knowledge_assistant.document_loader import (
    load_document,
    load_documents,
)

from knowledge_assistant.application import (
    KnowledgeAssistantApplication,
)
from knowledge_assistant.bootstrap import create_application
from knowledge_assistant.models import StartupTimings

logger = logging.getLogger(__name__)


def configure_logging(verbose: bool) -> None:
    """Configure application logging."""

    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.WARNING,
        format=(
            "%(asctime)s %(levelname)s "
            "%(name)s — %(message)s"
        ),
    )

def ingest_documents(
    application: KnowledgeAssistantApplication,
    source_path: Path | None,
) -> None:
    result = application.ingest(source_path)

    print(ConsoleFormatter.format_ingestion_result(result))


def search_documents(
    application: KnowledgeAssistantApplication,
    query: str,
    limit: int | None,
    strategy_name: str | None,
) -> None:
    results = application.search(
        query=query,
        limit=limit,
        strategy_name=strategy_name,
    )

    print(
        ConsoleFormatter.format_search_results(results)
    )


def show_stats(
    application: KnowledgeAssistantApplication,
) -> None:
    print(
        ConsoleFormatter.format_stats(
            application.stats()
        )
    )


def inspect_chunks(
    application: KnowledgeAssistantApplication,
    limit: int,
) -> None:
    records = application.inspect(limit=limit)

    print(
        ConsoleFormatter.format_records(records)
    )

def ask_question(
    application: KnowledgeAssistantApplication,
    query: str,
    limit: int | None,
) -> None:
    answer = application.ask(
        query=query,
        limit=limit,
    )

    print(answer.content)
    print()
    print("Sources:")
    print(
        ConsoleFormatter.format_search_results(
            list(answer.sources)
        )
    )
    print()
    print(
        f"Generated by: "
        f"{answer.provider_name}/{answer.model_name}"
    )

def explain_question(
    application: KnowledgeAssistantApplication,
    query: str,
    limit: int | None,
) -> None:
    trace = application.explain(
        query=query,
        limit=limit,
    )

    print(
        ConsoleFormatter.format_generation_trace(
            trace=trace,
            embedding_model_name=application.embedding_model_name,
            startup_timings=application.startup_timings,
        )
    )

def evaluate_retrieval(
    application: KnowledgeAssistantApplication,
    strategy_name: str,
    dataset_path: Path | None,
    top_k: int | None,
    include_details: bool,
    use_reranker: bool,
) -> None:
    """Evaluate configured retrieval strategies."""

    strategy_names = (
        ["vector", "bm25", "hybrid"]
        if strategy_name == "all"
        else [strategy_name]
    )

    outputs: list[str] = []

    for selected_strategy in strategy_names:
        summary = application.evaluate_retrieval(
            strategy_name=selected_strategy,
            dataset_path=dataset_path,
            top_k=top_k,
            use_reranker=use_reranker,
        )

        outputs.append(
            ConsoleFormatter.format_retrieval_evaluation(
                summary=summary,
                include_details=include_details,
            )
        )

    separator = "\n\n" + "=" * 70 + "\n\n"
    print(separator.join(outputs))


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line argument parser."""

    parser = argparse.ArgumentParser(
        prog="knowledge-assistant",
        description="Search local knowledge using semantic retrieval.",
    )

    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable diagnostic logging.",
    )

    subparsers = parser.add_subparsers(
        dest="command",
        required=True,
    )

    ingest_parser = subparsers.add_parser(
        "ingest",
        help="Load and index documents.",
    )

    ingest_parser.add_argument(
        "path",
        nargs="?",
        type=Path,
        default=None,
        help="File or directory to ingest. Default: documents/",
    )

    search_parser = subparsers.add_parser(
        "search",
        help="Search indexed documents.",
    )
    search_parser.add_argument(
        "query",
        help="Natural-language search query.",
    )
    search_parser.add_argument(
        "--limit",
        type=int,
        default=3,
        help="Maximum results to return. Default: 3.",
    )
    search_parser.add_argument(
        "--strategy",
        choices=["vector", "bm25", "hybrid"],
        default=None,
        help=(
            "Retrieval strategy override. "
            "Default: configured strategy."
        ),
    )

    subparsers.add_parser(
        "stats",
        help="Show index statistics.",
    )

    inspect_parser = subparsers.add_parser(
        "inspect",
        help="Inspect indexed chunks.",
    )
    inspect_parser.add_argument(
        "--limit",
        type=int,
        default=10,
        help="Maximum chunks to display. Default: 10.",
    )

    ask_parser = subparsers.add_parser(
        "ask",
        help="Answer a question using indexed documents.",
    )

    ask_parser.add_argument(
        "query",
        help="Natural-language question.",
    )

    ask_parser.add_argument(
        "--limit",
        type=int,
        default=3,
        help="Maximum source chunks to use. Default: 3.",
    )

    explain_parser = subparsers.add_parser(
        "explain",
        help="Show retrieval, prompt, and answer-generation details.",
    )

    explain_parser.add_argument(
        "query",
        help="Natural-language question.",
    )

    explain_parser.add_argument(
        "--limit",
        type=int,
        default=3,
        help="Maximum source chunks to use. Default: 3.",
    )

    evaluate_parser = subparsers.add_parser(
    "evaluate",
    help="Evaluate retrieval quality.",
    )

    evaluate_parser.add_argument(
        "--strategy",
        choices=["vector", "bm25", "hybrid", "all"],
        default="all",
        help="Strategy to evaluate. Default: all.",
    )

    evaluate_parser.add_argument(
        "--dataset",
        type=Path,
        default=None,
        help="Evaluation dataset path.",
    )

    evaluate_parser.add_argument(
        "--top-k",
        type=int,
        default=None,
        help="Number of retrieved results per case.",
    )

    evaluate_parser.add_argument(
        "--details",
        action="store_true",
        help="Display per-case evaluation results.",
    )

    evaluate_parser.add_argument(
        "--rerank",
        action="store_true",
        help="Apply the configured reranker before evaluation.",
    )

    return parser



def main(argv: Sequence[str] | None = None) -> None:
    cli_started = perf_counter()

    settings_started = perf_counter()
    settings = get_settings()
    settings_loading_ms = (
        perf_counter() - settings_started
    ) * 1000

    parser = build_parser()
    arguments = parser.parse_args(argv)
    configure_logging(arguments.verbose)

    try:
        construction_started = perf_counter()
        application = create_application(settings)
        dependency_construction_ms = (
            perf_counter() - construction_started
        ) * 1000

        total_startup_ms = (
            perf_counter() - cli_started
        ) * 1000

        startup_timings = StartupTimings(
            settings_loading_ms=settings_loading_ms,
            dependency_construction_ms=dependency_construction_ms,
            total_startup_ms=total_startup_ms,
        )

        application.record_startup_timings(startup_timings)

        logger.debug(
            "application_started settings_loading_ms=%.2f "
            "dependency_construction_ms=%.2f "
            "total_startup_ms=%.2f",
            settings_loading_ms,
            dependency_construction_ms,
            total_startup_ms,
        )

        if arguments.command == "ingest":
            ingest_documents(
                application=application,
                source_path=arguments.path,
            )

        elif arguments.command == "search":
            search_documents(
                application=application,
                query=arguments.query,
                limit=arguments.limit,
                strategy_name=arguments.strategy,
            )

        elif arguments.command == "ask":
            ask_question(
                application=application,
                query=arguments.query,
                limit=arguments.limit,
            )

        elif arguments.command == "explain":
            explain_question(
                application=application,
                query=arguments.query,
                limit=arguments.limit,
            )

        elif arguments.command == "stats":
            show_stats(application)

        elif arguments.command == "inspect":
            inspect_chunks(
                application=application,
                limit=arguments.limit,
            )

        elif arguments.command == "evaluate":
            evaluate_retrieval(
                application=application,
                strategy_name=arguments.strategy,
                dataset_path=arguments.dataset,
                top_k=arguments.top_k,
                include_details=arguments.details,
                use_reranker=arguments.rerank,
            )

        total_cli_ms = (perf_counter() - cli_started) * 1000

        logger.debug(
            "command_completed command=%s total_cli_ms=%.2f",
            arguments.command,
            total_cli_ms,
        )

    except (
        FileNotFoundError,
        RuntimeError,
        ValueError,
    ) as error:
        parser.error(str(error))



if __name__ == "__main__":
    main()