from knowledge_assistant.agent.models import (
    AgentResponse,
    FinalAnswerDecision,
    ToolCallDecision,
)
from knowledge_assistant.agent.citations import (
    format_agent_citation,
)

class AgentConsoleFormatter:
    """Format agent execution results for the CLI."""

    @staticmethod
    def format_response(
        response: AgentResponse,
        include_trace: bool = False,
    ) -> str:
        lines = [
            response.answer,
            "",
            (
                "Generated by: "
                f"{response.provider_name}/"
                f"{response.model_name}"
            ),
            "",
            (
                "Stopped reason: "
                f"{response.stop_reason}"
            ),
        ]

        if include_trace:
            lines.extend(
                [
                    "",
                    "AGENT TRACE",
                    "-" * 60,
                ]
            )

            for iteration in response.iterations:
                lines.extend(
                    [
                        f"Iteration: {iteration.iteration_number}",
                        "Component: Planner",
                    ]
                )

                decision = iteration.decision

                if isinstance(
                    decision,
                    ToolCallDecision,
                ):
                    lines.extend(
                        [
                            "Decision: call_tool",
                            (
                                "Selected tool: "
                                f"{decision.tool_call.tool_name}"
                            ),
                            (
                                "Arguments: "
                                f"{decision.tool_call.arguments}"
                            ),
                        ]
                    )

                    if iteration.tool_result is not None:
                        lines.extend(
                            [
                                "Component: Tool",
                                (
                                    "Tool: "
                                    f"{iteration.tool_result.tool_name}"
                                ),
                                "Observation:",
                                (
                                    iteration
                                    .tool_result
                                    .observation
                                    .content
                                ),
                            ]
                        )

                        observation = (
                            iteration.tool_result.observation
                        )

                        if observation.citations:
                            lines.append("Citations:")

                            for citation in (
                                observation.citations
                            ):
                                lines.append(
                                    "- "
                                    + format_agent_citation(
                                        citation
                                    )
                                )

                elif isinstance(
                    decision,
                    FinalAnswerDecision,
                ):
                    lines.extend(
                        [
                            "Decision: final_answer",
                            (
                                "Planner output: "
                                f"{decision.answer}"
                            ),
                        ]
                    )

                lines.append("")

            if response.steps:
                lines.extend(
                    [
                        "FINAL SYNTHESIS",
                        "-" * 60,
                        "Component: Synthesizer",
                        (
                            "Model: "
                            f"{response.provider_name}/"
                            f"{response.model_name}"
                        ),
                        "Answer:",
                        response.answer,
                    ]
                )

            grounding = response.grounding_validation

            if grounding is not None:
                supported_count = len(
                    grounding.supported_claims
                )
                unsupported_count = len(
                    grounding.unsupported_claims
                )

                lines.extend(
                    [
                        "",
                        "GROUNDING VALIDATION",
                        "-" * 60,
                        "Component: Grounding Validator",
                        (
                            "Status: "
                            + (
                                "PASSED"
                                if grounding.is_grounded
                                else "FAILED"
                            )
                        ),
                        f"Checked claims: {len(grounding.claims)}",
                        f"Supported: {supported_count}",
                        f"Unsupported: {unsupported_count}",
                    ]
                )

                if grounding.unsupported_claims:
                    lines.append("")
                    lines.append("Unsupported claims:")

                    for claim in grounding.unsupported_claims:
                        lines.extend(
                            [
                                f'- "{claim.sentence}"',
                                f"  Reason: {claim.reason}",
                            ]
                        )
                else:
                    lines.append(
                        "All factual claims are supported "
                        "by the selected evidence."
                    )

                        
                        
        return "\n".join(lines).rstrip()